### PR TITLE
Migrated to new MSBuild tooling

### PR DESCRIPTION
**Pull request by josephwoodward**

### CODE REVIEW

**Comment by pgermishuys** [comment]
Build is failing due to
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: src/EventStore.ClientAPI.NetCore/project.json
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by josephwoodward** [comment]
Yeah, just fixing those now. Hopefully this will work 🤞

**Comment by josephwoodward** [comment]
Out of interest, is the long term plan to keep this client separate from the other, or merge the two?

**Comment by josephwoodward** [comment]
```bash
Fri Jul 7 13:05:51 UTC 2017 - building ...
Fri Jul 7 13:06:21 UTC 2017 - building ...
Fri Jul 7 13:06:51 UTC 2017 - building ...
Fri Jul 7 13:07:21 UTC 2017 - building ...
Fri Jul 7 13:07:51 UTC 2017 - building ...
Fri Jul 7 13:08:21 UTC 2017 - building ...
Fri Jul 7 13:08:51 UTC 2017 - building ...
Fri Jul 7 13:09:21 UTC 2017 - building ...
Fri Jul 7 13:09:51 UTC 2017 - building ...
Fri Jul 7 13:10:21 UTC 2017 - building ...
```

I see this when trying to run the tests locally via the `run_suppressed_tests.sh` script, looks like the build server is stuck in the loop too. Any ideas?

**Comment by pgermishuys** [comment]
Yes, that's expected behaviour.

**Comment by pgermishuys** [comment]
If you flood the build server's std out with too much output it fails the build, if you don't report anything, it times out and fails the build. So the script is attempting to just keep the build alive by writing a message every 30 seconds.

This can be reviewed as this was the case with travis not sure if wercker requires the same behaviour.

**Comment by pgermishuys** [comment]
@JosephWoodward also investigating as the tests should not be taking this long.

**Comment by josephwoodward** [comment]
@pgermishuys Yeah, this is what I was thinking.

**Comment by pgermishuys** [comment]
@JosephWoodward this might be related to the client being 4.x and I see you have reverted the server to a 3.9.3.

**Comment by pgermishuys** [comment]
Thanks @JosephWoodward. You are on commit form!

**Comment by pgermishuys** [comment]
Tests shouldn't be taking longer than a minute or so.

**Comment by josephwoodward** [comment]
Here's the output if I run the tests locally:

```bash
Failed   should_append_with_stream_exists_exp_ver_if_metadata_stream_exists
Error Message:
 System.AggregateException : One or more errors occurred. (Connection 'ESC-12' was closed.)
  ----> EventStore.ClientAPI.Exceptions.ConnectionClosedException : Connection 'ESC-12' was closed.
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eventstore.ClientAPI.Tests.append_to_stream.should_append_with_stream_exists_exp_ver_if_metadata_stream_exists() in /Users/josephwoodward/Dev/EventStore/ClientAPI.NetCore/test/EventStore.ClientAPI.NetCore.Tests/append_to_stream.cs:line 295
--ConnectionClosedException
Standard Output Messages:
 [06,13:33:13.300,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.StartConnectionMessage..
 [09,13:33:13.300,DEBUG] EventStoreConnection 'ESC-12': StartConnection.
 [09,13:33:13.300,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [09,13:33:13.300,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [09,13:33:13.300,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [09,13:33:13.301,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {88efe807-d3bc-4907-8be7-5bbe27a673be}] failed. Error: ConnectionRefused.
 [09,13:33:13.301,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [09,13:33:13.301,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {88efe807-d3bc-4907-8be7-5bbe27a673be}] closed..
 [06,13:33:13.311,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.StartOperationMessage..
 [09,13:33:13.312,DEBUG] EventStoreConnection 'ESC-12': StartOperation enqueue AppendToStreamOperation, Stream: $$should_append_with_stream_exists_exp_ver_if_metadata_stream_exists, ExpectedVersion: -2, 100, 1.00:00:00..
 [09,13:33:13.312,DEBUG] EventStoreConnection 'ESC-12': EnqueueOperation WAITING for Operation AppendToStreamOperation (257b3467-ccf4-4ff8-8531-e54353df0504): Stream: $$should_append_with_stream_exists_exp_ver_if_metadata_stream_exists, ExpectedVersion: -2, retry count: 0, created: 13:33:13.312, last updated: 13:33:13.312..
 [14,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [14,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [14,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [14,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [09,13:33:13.500,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {ebef0a09-40cb-4c94-9650-f05df1e7796b}] failed. Error: ConnectionRefused.
 [09,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [09,13:33:13.500,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {ebef0a09-40cb-4c94-9650-f05df1e7796b}] closed..
 [10,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [14,13:33:13.701,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {2744da75-023b-4f05-ad72-c34902a712db}] failed. Error: ConnectionRefused.
 [14,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [14,13:33:13.701,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {2744da75-023b-4f05-ad72-c34902a712db}] closed..
 [14,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [14,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [14,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [14,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [13,13:33:13.902,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {15f617f2-50cc-4a37-8d06-033630028720}] failed. Error: ConnectionRefused.
 [13,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [13,13:33:13.902,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {15f617f2-50cc-4a37-8d06-033630028720}] closed..
 [10,13:33:14.102,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:14.102,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:14.102,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:14.102,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [14,13:33:14.103,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {8a7777e5-2643-404c-b281-97e2b2aed8a5}] failed. Error: ConnectionRefused.
 [14,13:33:14.103,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [14,13:33:14.103,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {8a7777e5-2643-404c-b281-97e2b2aed8a5}] closed..
 [10,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [14,13:33:14.305,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {aa8210e1-2897-4e71-b7c3-c2a796e510fe}] failed. Error: ConnectionRefused.
 [14,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [14,13:33:14.305,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {aa8210e1-2897-4e71-b7c3-c2a796e510fe}] closed..
 [13,13:33:14.510,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [13,13:33:14.510,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [13,13:33:14.510,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:14.510,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [14,13:33:14.511,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {a287772c-2fef-46e7-a467-5a6272f8538c}] failed. Error: ConnectionRefused.
 [14,13:33:14.511,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [14,13:33:14.511,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {a287772c-2fef-46e7-a467-5a6272f8538c}] closed..
 [09,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [09,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [09,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [09,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [13,13:33:14.715,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {9377db64-1d0a-4835-afba-19094e8f3737}] failed. Error: ConnectionRefused.
 [13,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [13,13:33:14.715,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {9377db64-1d0a-4835-afba-19094e8f3737}] closed..
 [10,13:33:14.918,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:14.918,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:14.918,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:14.918,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [10,13:33:14.919,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {3954a988-fbc6-4c23-a8fa-f9fb0ba9b094}] failed. Error: ConnectionRefused.
 [10,13:33:14.919,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [10,13:33:14.919,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {3954a988-fbc6-4c23-a8fa-f9fb0ba9b094}] closed..
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [10,13:33:15.121,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {012b127d-8fa5-4a5e-93e1-4e3cba531406}] failed. Error: ConnectionRefused.
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [10,13:33:15.121,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {012b127d-8fa5-4a5e-93e1-4e3cba531406}] closed..
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': DiscoverEndPoint.
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': EstablishTcpConnection to [127.0.0.1:1113].
 [10,13:33:15.325,DEBUG] TcpPackageConnection: connection to [127.0.0.1:1113, L, {cb4f5020-b84e-432a-8ab4-9707ae6a6655}] failed. Error: ConnectionRefused.
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [10,13:33:15.325,DEBUG] EventStoreConnection 'ESC-12': TCP connection to [127.0.0.1:1113, L, {cb4f5020-b84e-432a-8ab4-9707ae6a6655}] closed..
 [10,13:33:15.527,DEBUG] EventStoreConnection 'ESC-12': TimerTick checking reconnection....
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': CloseConnection, reason Reconnection limit reached., exception ..
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': CloseTcpConnection.
 [10,13:33:15.528,INFO] ClientAPI TcpConnection closed [13:33:15.528: N127.0.0.1:1113, L, {cb4f5020-b84e-432a-8ab4-9707ae6a6655}]:
 [10,13:33:15.528,INFO] Received bytes: 0, Sent bytes: 0
 [10,13:33:15.528,INFO] Send calls: 0, callbacks: 0
 [10,13:33:15.528,INFO] Receive calls: 0, callbacks: 0
 [10,13:33:15.528,INFO] Close reason: [Success] Reconnection limit reached.
 [10,13:33:15.528,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L, {cb4f5020-b84e-432a-8ab4-9707ae6a6655}] was closed cleanly.
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': IGNORED (_state: Closed, _conn.ID: {cb4f5020-b84e-432a-8ab4-9707ae6a6655}, conn.ID: {cb4f5020-b84e-432a-8ab4-9707ae6a6655}): TCP connection to [127.0.0.1:1113, L] closed..
 [10,13:33:15.528,INFO] EventStoreConnection 'ESC-12': Closed. Reason: Reconnection limit reached...
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': IGNORED (_state: Closed, _conn.ID: {00000000-0000-0000-0000-000000000000}, conn.ID: {cb4f5020-b84e-432a-8ab4-9707ae6a6655}): TCP connection to [127.0.0.1:1113, L] closed..
 [06,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': enqueueing message EventStore.ClientAPI.Internal.CloseConnectionMessage..
 [10,13:33:15.528,DEBUG] EventStoreConnection 'ESC-12': CloseConnection IGNORED because is ESConnection is CLOSED, reason Connection close requested by client., exception ..

Failed   should_append_with_stream_exists_exp_ver_to_existing_stream
Error Message:
 System.AggregateException : One or more errors occurred. (Connection 'ESC-13' was closed.)
  ----> EventStore.ClientAPI.Exceptions.ConnectionClosedException : Connection 'ESC-13' was closed.
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Eventstore.ClientAPI.Tests.append_to_stream.should_append_with_stream_exists_exp_ver_to_existing_stream() in /Users/josephwoodward/Dev/EventStore/ClientAPI.NetCore/test/EventStore.ClientAPI.NetCore.Tests/append_to_stream.cs:line 263
--ConnectionClosedException
```

**Comment by hayley-jean** [comment]
@JosephWoodward I'll look into this quickly and see if I can figure out what's going on

**Comment by josephwoodward** [comment]
@hayley-jean Thanks, that would be great. I'll be around for a few more hours so can jump on any changes right away. As I can't get the tests running locally I'm not sure if it's something I've done so I'm flying blind.

**Comment by hayley-jean** [comment]
@JosephWoodward I'm also having trouble running the tests locally. I'll try sort it out on Monday and let you know if I find anything

**Comment by josephwoodward** [comment]
Thanks, I'll keep an eye on this then. If you need me to make any changes then just let me know.

**Comment by pgermishuys** [comment]
Here's the output from a test run on a fresh ubuntu 16.04 box.

```
Total tests: 516. Passed: 491. Failed: 4. Skipped: 21.
Test execution time: 45.0827 Seconds
Test Run Failed.
```

**Comment by pgermishuys** [comment]
@JosephWoodward in the sake of moving this forward, we are going to be pushing up a working branch and get this done.

**Comment by pgermishuys** [comment]
ok! moving forward with this, we have identified the issues with the CI server and going to get those fixed.

**Comment by pgermishuys** [comment]
@JosephWoodward closing this PR in favour of the [PR ](https://github.com/EventStore/ClientAPI.NetCore/pull/12) with your commits as well as a passing build.

**Pull request closed without merging**
