### PR TITLE
migrate to latest csproj format

### PR DESCRIPTION
**Pull request by alistair**
I havent checked that the functional tests still run successfully yet.

### CODE REVIEW

**Comment by pgermishuys** [comment]
Thanks for the PR @alistair. Will need to get the PR statuses working. Will do that soonest.

**Comment by pgermishuys** [comment]
@jageall is the work that you are doing on the following [branch](https://github.com/EventStore/ClientAPI.NetCore/tree/update-for-4.0) related to this PR? The reason @alistair's PR hasn't been merged yet is because the tests aren't running which i'm in the process of resolving. Is there a way we can still make use of @alistair's work?

**Comment by pgermishuys** [comment]
The status checks should now run @alistair if you force push your branch up again. My apologies for this having taken so long.

**Comment by josephwoodward** [comment]
What's happening with this PR? Happy to fork it and push it again if @alistair isn't replying?

**Comment by pgermishuys** [comment]
Sure, this needs to move forward. Thanks @JosephWoodward

**Comment by josephwoodward** [comment]
Doing it now 👍

**Comment by josephwoodward** [comment]
Created a PR here (https://github.com/EventStore/ClientAPI.NetCore/pull/11), couldn't get the tests running locally so waiting to see if the build/tests pass.

**Pull request closed without merging**
